### PR TITLE
A state without "data.css" applied didn't work

### PR DESCRIPTION
**Pull request by harm-less**
It threw an error because "css" cannot be found in "data".

### CODE REVIEW

**Comment by harm-less** [comment]
Are there any plans to merge the pull-request made?

**Comment by slavafomin** [comment]
Hello @harm-less!

Thank you for your interest in this module and your work. I really appreciate it!

However, my time is extremely limited these days, so I'm not able to address the issues. I would suggest to create a fork for the time being. I will try to review these issues when time permits.

Thanks again!

**Comment by harm-less** [comment]
All right, I guess many of us are having that same problem. Would you be ok if I help you out and include me in a Betsol Github Team? Then you only need to give me access to this repository.

**Comment by chrisengelsma** [comment]
I highly recommend merging this one in. I've been trying to figure out why I was getting this error and this solves it

**Pull request merged**
